# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    token_authenticator:
        class: GuideTouristiqueBundle\Security\TokenAuthenticator
        arguments: ['@lexik_jwt_authentication.encoder.default', '@doctrine.odm.mongodb.document_manager']

#//////////////////////////////////////////serviceimpdao////////////////////////////////////////////




    s.type_publicite.impdao:
        class:     GuideTouristiqueBundle\Dao\ImpDao\PackImpDao\TypePubliciteImpDao
        arguments: ['@doctrine.odm.mongodb.document_manager']

    s.publicite.impdao:
        class:     GuideTouristiqueBundle\Dao\ImpDao\PackImpDao\PubliciteImpDao
        arguments: ['@doctrine.odm.mongodb.document_manager']


    s.visite_virtuelle.impdao:
        class:     GuideTouristiqueBundle\Dao\ImpDao\PackImpDao\VisiteVirtuelleImpDao
        arguments: ['@doctrine.odm.mongodb.document_manager']

    s.cpack_publicite.impdao:
        class:     GuideTouristiqueBundle\Dao\ImpDao\PackImpDao\CpackPubliciteImpDao
        arguments: ['@doctrine.odm.mongodb.document_manager']


    s.categorie.impdao:
        class:     GuideTouristiqueBundle\Dao\ImpDao\PackImpDao\CategorieImpDao
        arguments: ['@doctrine.odm.mongodb.document_manager']

    s.fiche_technique.impdao:
        class:     GuideTouristiqueBundle\Dao\ImpDao\PackImpDao\FicheTechniqueImpDao
        arguments: ['@doctrine.odm.mongodb.document_manager']

    s.offre.impdao:
        class:     GuideTouristiqueBundle\Dao\ImpDao\PackImpDao\OffreImpDao
        arguments: ['@doctrine.odm.mongodb.document_manager']

    s.cpack_fiche_technique.impdao:
        class:     GuideTouristiqueBundle\Dao\ImpDao\PackImpDao\CpackFicheTechniqueImpDao
        arguments: ['@doctrine.odm.mongodb.document_manager']

    s.pack.impdao:
        class:     GuideTouristiqueBundle\Dao\ImpDao\PackImpDao\PackImpDao
        arguments: ['@doctrine.odm.mongodb.document_manager']


    s.image.impdao:
            class:     GuideTouristiqueBundle\Dao\ImpDao\ImageImpDao
            arguments: ['@doctrine.odm.mongodb.document_manager']

    s.video.impdao:
            class:     GuideTouristiqueBundle\Dao\ImpDao\VideoImpDao
            arguments: ['@doctrine.odm.mongodb.document_manager']

    s.offreMedia.impdao:
            class:     GuideTouristiqueBundle\Dao\ImpDao\PackImpDao\OffreMediaImpDao
            arguments: ['@doctrine.odm.mongodb.document_manager']

    s.cpack_image.impdao:
        class:     GuideTouristiqueBundle\Dao\ImpDao\PackImpDao\CpackImageImpDao
        arguments: ['@doctrine.odm.mongodb.document_manager']

    s.cpack_video.impdao:
        class:     GuideTouristiqueBundle\Dao\ImpDao\PackImpDao\CpackVideoImpDao
        arguments: ['@doctrine.odm.mongodb.document_manager']

    s.offre_fiche_technique.impdao:
        class:     GuideTouristiqueBundle\Dao\ImpDao\PackImpDao\OffreFicheTechniqueImpDao
        arguments: ['@doctrine.odm.mongodb.document_manager']

    s.offre_video.impdao:
        class:     GuideTouristiqueBundle\Dao\ImpDao\PackImpDao\OffreVideoImpDao
        arguments: ['@doctrine.odm.mongodb.document_manager']

    s.offre_image.impdao:
        class:     GuideTouristiqueBundle\Dao\ImpDao\PackImpDao\OffreImageImpDao
        arguments: ['@doctrine.odm.mongodb.document_manager']

    s.offre_publicite.impdao:
        class:     GuideTouristiqueBundle\Dao\ImpDao\PackImpDao\OffrePubliciteImpDao
        arguments: ['@doctrine.odm.mongodb.document_manager']

    s.cpack_visite_virtuelle.impdao:
        class:     GuideTouristiqueBundle\Dao\ImpDao\PackImpDao\CpackVisiteVirtuelleImpDao
        arguments: ['@doctrine.odm.mongodb.document_manager']


    s.offre_visite_virtuelle.impdao:
        class:     GuideTouristiqueBundle\Dao\ImpDao\PackImpDao\OffreVisiteVirtuelleImpDao
        arguments: ['@doctrine.odm.mongodb.document_manager']


    s.devise.impdao:
        class:     GuideTouristiqueBundle\Dao\ImpDao\DeviseImpDao
        arguments: ['@doctrine.odm.mongodb.document_manager']

    s.etat.impdao:
        class:     GuideTouristiqueBundle\Dao\ImpDao\EtatImpDao
        arguments: ['@doctrine.odm.mongodb.document_manager']


    s.duree.impdao:
        class:     GuideTouristiqueBundle\Dao\ImpDao\DureeImpDao
        arguments: ['@doctrine.odm.mongodb.document_manager']

    s.commentaire.impdao:
        class:     GuideTouristiqueBundle\Dao\ImpDao\CommentaireImpDao
        arguments: ['@doctrine.odm.mongodb.document_manager']

    s.langue.impdao:
        class:     GuideTouristiqueBundle\Dao\ImpDao\LangueImpDao
        arguments: ['@doctrine.odm.mongodb.document_manager']

    s.actualite.impdao:
        class:     GuideTouristiqueBundle\Dao\ImpDao\PublicationImpDao\ActualiteImpDao
        arguments: ['@doctrine.odm.mongodb.document_manager']

    s.actualite_traduction.impdao:
        class:     GuideTouristiqueBundle\Dao\ImpDao\PublicationImpDao\ActualiteTraductionImpDao
        arguments: ['@doctrine.odm.mongodb.document_manager']

    s.evenement_traduction.impdao:
        class:     GuideTouristiqueBundle\Dao\ImpDao\PublicationImpDao\EvenementTraductionImpDao
        arguments: ['@doctrine.odm.mongodb.document_manager']

    s.evenement.impdao:
        class:     GuideTouristiqueBundle\Dao\ImpDao\PublicationImpDao\EvenementImpDao
        arguments: ['@doctrine.odm.mongodb.document_manager']

    s.tache.impdao:
        class:     GuideTouristiqueBundle\Dao\ImpDao\TacheImpDao\TacheImpDao
        arguments: ['@doctrine.odm.mongodb.document_manager']

    s.admin.impdao:
        class:     GuideTouristiqueBundle\Dao\ImpDao\CompteImpDao\AdminImpDao
        arguments: ['@doctrine.odm.mongodb.document_manager']

    s.adresse.impdao:
        class:     GuideTouristiqueBundle\Dao\ImpDao\AdresseImpDao
        arguments: ['@doctrine.odm.mongodb.document_manager']


    s.client_vente.impdao:
        class:     GuideTouristiqueBundle\Dao\ImpDao\CompteImpDao\ClientVenteImpDao
        arguments: ['@doctrine.odm.mongodb.document_manager']

    s.client_achat.impdao:
        class:     GuideTouristiqueBundle\Dao\ImpDao\CompteImpDao\ClientAchatImpDao
        arguments: ['@doctrine.odm.mongodb.document_manager']

    s.client.impdao:
        class:     GuideTouristiqueBundle\Dao\ImpDao\CompteImpDao\ClientImpDao
        arguments: ['@doctrine.odm.mongodb.document_manager']


    s.type_client_vente.impdao:
        class:     GuideTouristiqueBundle\Dao\ImpDao\CompteImpDao\TypeClientVenteImpDao
        arguments: ['@doctrine.odm.mongodb.document_manager']

    s.responsable.impdao:
        class:     GuideTouristiqueBundle\Dao\ImpDao\CompteImpDao\ResponsableImpDao
        arguments: ['@doctrine.odm.mongodb.document_manager']






#////////////////////////////////////////////ImpMetier////////////////////////////////////////////////////////////

    s.offre_fiche_technique.impmetier:
              class: GuideTouristiqueBundle\Metier\ImpMetier\PackImpMetier\OffreFicheTechniqueImpMetier
              arguments:  ['@s.offre_fiche_technique.impdao','@s.image.impmetier','@s.duree.impmetier','@s.etat.impmetier','@s.devise.impmetier']

    s.offre_video.impmetier:
              class: GuideTouristiqueBundle\Metier\ImpMetier\PackImpMetier\OffreVideoImpMetier
              arguments:  ['@s.offre_video.impdao','@s.image.impmetier','@s.duree.impmetier','@s.etat.impmetier','@s.devise.impmetier']

    s.offre_image.impmetier:
              class: GuideTouristiqueBundle\Metier\ImpMetier\PackImpMetier\OffreImageImpMetier
              arguments:  ['@s.offre_image.impdao','@s.image.impmetier','@s.duree.impmetier','@s.etat.impmetier','@s.devise.impmetier']

    s.offre_publicite.impmetier:
              class: GuideTouristiqueBundle\Metier\ImpMetier\PackImpMetier\OffrePubliciteImpMetier
              arguments:  ['@s.offre_publicite.impdao','@s.image.impmetier','@s.duree.impmetier','@s.etat.impmetier','@s.devise.impmetier']


    s.offre_visite_virtuelle.impmetier:
              class: GuideTouristiqueBundle\Metier\ImpMetier\PackImpMetier\OffreVisiteVirtuelleImpMeter
              arguments:  ['@s.offre_visite_virtuelle.impdao','@s.image.impmetier','@s.duree.impmetier','@s.etat.impmetier','@s.devise.impmetier']

    s.duree.impmetier:
              class: GuideTouristiqueBundle\Metier\ImpMetier\DureeImpMetier
              arguments:  ['@s.duree.impdao']



    s.categorie.impmetier:
              class: GuideTouristiqueBundle\Metier\ImpMetier\PackImpMetier\CategorieImpMetier
              arguments:  ['@s.categorie.impdao','@s.image.impmetier','@s.etat.impmetier']

    s.tache.impmetier:
              class: GuideTouristiqueBundle\Metier\ImpMetier\TacheImpMetier\TacheImpMetier
              arguments:  ['@s.tache.impdao','@s.admin.impmetier','@s.etat.impmetier']

    s.type_client_vente.impmetier:
              class: GuideTouristiqueBundle\Metier\ImpMetier\CompteImpMetier\ClientVenteTypeImpMetier
              arguments:  ['@s.type_client_vente.impdao','@s.etat.impmetier','@s.langue.impmetier']

    s.responsable.impmetier:
              class: GuideTouristiqueBundle\Metier\ImpMetier\CompteImpMetier\ResponsableImpMetier
              arguments:  ['@s.responsable.impdao']


    s.client_vente.impmetier:
              class: GuideTouristiqueBundle\Metier\ImpMetier\CompteImpMetier\ClientVenteImpMetier
              arguments:  ['@s.client_vente.impdao','@s.etat.impmetier','@s.type_client_vente.impmetier','@s.responsable.impmetier','@s.adresse.impmetier','@s.image.impmetier']

    s.client_achat.impmetier:
              class: GuideTouristiqueBundle\Metier\ImpMetier\CompteImpMetier\ClientAchatImpMetier
              arguments:  ['@s.client_achat.impdao','@s.etat.impmetier','@s.adresse.impmetier','@s.image.impmetier']

    s.client.impmetier:
              class: GuideTouristiqueBundle\Metier\ImpMetier\CompteImpMetier\ClientImpMetier
              arguments:  ['@s.client.impdao','@security.password_encoder','@s.etat.impmetier']



    s.admin.impmetier:
              class: GuideTouristiqueBundle\Metier\ImpMetier\CompteImpMetier\AdminImpMetier
              arguments:  ['@s.admin.impdao','@security.password_encoder','@s.etat.impmetier']


    s.langue.impmetier:
              class: GuideTouristiqueBundle\Metier\ImpMetier\LangueImpMetier
              arguments:  ['@s.langue.impdao','@s.etat.impmetier']

    s.actualite.impmetier:
              class: GuideTouristiqueBundle\Metier\ImpMetier\PublicationImpMetier\ActualiteImpMetier
              arguments:  ['@s.actualite.impdao','@s.etat.impmetier','@s.actualite_traduction.impmetier','@s.commentaire.impmetier']

    s.evenement.impmetier:
              class: GuideTouristiqueBundle\Metier\ImpMetier\PublicationImpMetier\EvenementImpMetier
              arguments:  ['@s.evenement.impdao','@s.etat.impmetier','@s.evenement_traduction.impmetier','@s.commentaire.impmetier']

    s.actualite_traduction.impmetier:
              class: GuideTouristiqueBundle\Metier\ImpMetier\PublicationImpMetier\ActualiteTraductionImpMetier
              arguments:  ['@s.actualite_traduction.impdao','@s.langue.impmetier']

    s.evenement_traduction.impmetier:
              class: GuideTouristiqueBundle\Metier\ImpMetier\PublicationImpMetier\EvenementTraductionImpMetier
              arguments:  ['@s.evenement_traduction.impdao','@s.langue.impmetier']


    s.fiche_technique.impmetier:
              class: GuideTouristiqueBundle\Metier\ImpMetier\PackImpMetier\FicheTechniqueImpMetier
              arguments:  ['@s.fiche_technique.impdao']

    s.offre.impmetier:
              class: GuideTouristiqueBundle\Metier\ImpMetier\PackImpMetier\OffreImpMetier
              arguments:  ['@s.offre.impdao']

    s.cpack_fiche_technique.impmetier:
              class: GuideTouristiqueBundle\Metier\ImpMetier\PackImpMetier\CpackFicheTechniqueImpMetier
              arguments:  ['@s.cpack_fiche_technique.impdao','@s.offre_fiche_technique.impmetier','@s.categorie.impmetier','@s.fiche_technique.impmetier']

    s.cpack_visite_virtuelle.impmetier:
              class: GuideTouristiqueBundle\Metier\ImpMetier\PackImpMetier\CpackVisiteVirtuelleImpMetier
              arguments:  ['@s.cpack_visite_virtuelle.impdao','@s.offre_visite_virtuelle.impmetier','@s.categorie.impmetier','@s.visite_virtuelle.impmetier']

    s.visite_virtuelle.impmetier:
              class: GuideTouristiqueBundle\Metier\ImpMetier\PackImpMetier\VisiteVirtuelleImpMetier
              arguments:  ['@s.visite_virtuelle.impdao']



    s.type_publicite.impmetier:
              class: GuideTouristiqueBundle\Metier\ImpMetier\PackImpMetier\TypePubliciteImpMetier
              arguments:  ['@s.type_publicite.impdao']


    s.publicite.impmetier:
              class: GuideTouristiqueBundle\Metier\ImpMetier\PackImpMetier\PubliciteImpMetier
              arguments:  ['@s.publicite.impdao','@s.type_publicite.impmetier','@s.image.impmetier']




    s.cpack_publicite.impmetier:
              class: GuideTouristiqueBundle\Metier\ImpMetier\PackImpMetier\CpackPublicteImpMetier
              arguments:  ['@s.cpack_publicite.impdao','@s.offre_publicite.impmetier','@s.categorie.impmetier','@s.publicite.impmetier']



    s.image.impmetier:
                  class: GuideTouristiqueBundle\Metier\ImpMetier\ImageImpMetier
                  arguments:  ['@s.image.impdao']

    s.video.impmetier:
                  class: GuideTouristiqueBundle\Metier\ImpMetier\VideoImpMetier
                  arguments:  ['@s.video.impdao']

    s.offreMedia.impmetier:
              class: GuideTouristiqueBundle\Metier\ImpMetier\PackImpMetier\OffreMediaImpMetier
              arguments:  ['@s.offreMedia.impdao']

    s.cpack_image.impmetier:
              class: GuideTouristiqueBundle\Metier\ImpMetier\PackImpMetier\CpackImageImpMetier
              arguments:  ['@s.cpack_image.impdao','@s.offre_image.impmetier','@s.categorie.impmetier','@s.image.impmetier']


    s.cpack_video.impmetier:
              class: GuideTouristiqueBundle\Metier\ImpMetier\PackImpMetier\CpackVideoImpMetier
              arguments:  ['@s.cpack_video.impdao','@s.offre_video.impmetier','@s.categorie.impmetier','@s.video.impmetier']

    s.pack.impmetier:
                  class: GuideTouristiqueBundle\Metier\ImpMetier\PackImpMetier\PackImpMetier
                  arguments:  ['@s.pack.impdao','@s.cpack_fiche_technique.impmetier','@s.cpack_image.impmetier','@s.cpack_video.impmetier','@s.cpack_publicite.impmetier','@s.cpack_visite_virtuelle.impmetier',]

    s.devise.impmetier:
              class: GuideTouristiqueBundle\Metier\ImpMetier\DeviseImpMetier
              arguments:  ['@s.devise.impdao','@s.etat.impmetier']


    s.commentaire.impmetier:
              class: GuideTouristiqueBundle\Metier\ImpMetier\CommentaireImpMetier
              arguments:  ['@s.commentaire.impdao','@s.etat.impmetier']

    s.etat.impmetier:
              class: GuideTouristiqueBundle\Metier\ImpMetier\EtatImpMetier
              arguments:  ['@s.etat.impdao']

    s.adresse.impmetier:
              class: GuideTouristiqueBundle\Metier\ImpMetier\AdresseImpMetier
              arguments:  ['@s.adresse.impdao']
